### ISSUE TITLE
[eigenaar]Veiling automatisch afsluiten

### ISSUE THREAD

**Issue by SoulfIy** [EenmaalAndermaal/EenmaalAndermaal#103]
# Gerelateerde issues
  - #
  - #

# Omschrijving
Als eigenaar wil ik dat veilingen beëindigd worden.

wanneer de tijd verstreken is of handmatig beëindigd is.

Definitions of Done:
-[] veiling is beëindigd - staat op status: beëindigd
-[] beëindigen van veiling is bevestigd

**Comment by bartkessels** [comment]
Duplicate #84
