### ISSUE TITLE
Hoogste bod weergave klopt niet

### ISSUE THREAD

**Issue by SoulfIy** [EenmaalAndermaal/EenmaalAndermaal#129]
# Gerelateerde issues
  - #
  - #

# Omschrijving
~in de zoekresultaten staat iets, (hier komt ieder bod op hetzelfde item apart voor)~
~op de detailpagina staat iets anders in de (h2?)~ -> Non-issue
~op de detialpagina staat WEER iets anders bij 'hoogste bod'~ -> Non-issue

**Comment by bartkessels** [comment]
Duplicate #135
Overige items die er staan slaan nergens op
