### ISSUE TITLE
Eindpresentatie

### ISSUE THREAD

**Issue by svenvNL** [EenmaalAndermaal/EenmaalAndermaal#184]
- [x] Correcte PowerPoint

- [x] Site ingericht met correcte data

- [x] Koper, verkoper en beheerdersaccount aanwezig in de database en de accountdetails bekend in het team

- [x] Value functionaliteit word bekend

- [x] De presentatie motiveert om het product te kopen

**Comment by bartkessels** [comment]
Is gefixt!
