### ISSUE TITLE
Breadcrumbs & bovenstaande categorie weergave in categorieen

### ISSUE THREAD

**Issue by SoulfIy** [EenmaalAndermaal/EenmaalAndermaal#95]
# Gerelateerde issues
  - #
  - #

# Omschrijving
als je een categorie aanklikt moet dit nog weergegeven worden in de breadcrumb
en de bovenstaande categorie moet nog weergegeven worden

**Comment by svenvNL** [comment]
Moet met php while loops op database, vraagt teveel system resources voor wat het levert
